### ISSUE TITLE
MMS support

### ISSUE THREAD

**Issue by robertoamoreno** [jpwalters/OpenVBX-Plugin-SMS-Conversation#22]
would be great to get MMS support

**Comment by jpwalters** [comment]
The plugin does already support receiving MMS messages and we're currently working on making it support sending MMS message.  You can checkout issue #9 which I've already written the code for.  

The hold up on releasing that feature is we're waiting on OpenVBX to approve our pull request and release a new version since it requires an enhancement to the core project.  Feel free to checkout our pull request and make some noise there to encourage them to including it.  [OpenVBX Pull Request](https://github.com/twilio/OpenVBX/pull/366)

**Comment by jpwalters** [comment]
Since this issue duplicates issues #9 I'm going to close it.  If you feel that issue #9 doesn't full express the feature you'd like to have added feel free to drop your comments on that issue and we'll see what we can do to enhance it.
